---

- name: install mdns NSS module
  package:
    name: libnss-mdns
    state: present
  when: not(mdns_server_only|default('false')|bool)
  become: true

- name: install avahi daemon
  package:
    name: avahi-daemon
    state: present
  become: true

- name: enable avahi daemon
  service:
    name: avahi-daemon
    enabled: yes
    state: started
