---

- name: install mkimage
  apt_rpm: pkg={{ item }} state=present
  with_items:
    - mkimage
    - mkimage-preinstall
    - git-core
  notify: apply sysctl.d knobs
  become: true

- name: add user to wheel group
  user:
    name: "{{ hasher_user }}"
    groups: wheel
    append: true
  become: true
  when:
    - hasher_user is defined
    - hasher_enable_wheel|default(true)|bool

- name: enable passwordless sudo for user
  copy:
    dest: "/etc/sudoers.d/{{ hasher_user }}"
    owner: root
    group: root
    mode: 0600
    content: "{{ hasher_user }} ALL=(ALL) NOPASSWD: ALL"
  become: true
  when:
    - hasher_user is defined
    - hasher_enable_nopasswd_sudo|default(true)|bool
