---

- set_fact:
    kernel_build_packages:
      - bison
      - build-essential
      - ccache
      - dh-exec
      - dwarves
      - git
      - fakeroot
      - flex
      - libelf-dev
      - libncursesw5-dev 
      - libtinfo-dev
      - libssl-dev
      - openssl
      - u-boot-tools
  when:
    ansible_os_family == 'Debian'

- set_fact:
    kernel_build_packages:
      - bc
      - bison
      - ccache
      - cpio
      - dwarves
      - gcc
      - git-core
      - fakeroot
      - flex
      - libelf-devel
      - libncursesw-devel
      - libtinfo-devel
      - libssl-devel
      - make
      - openssl
      - u-boot-tools
  when: ansible_distribution_file_path == '/etc/altlinux-release'

- name: install basic C development tools
  package: name={{ item }} state=present
  with_items: "{{ kernel_build_packages }}"
  become: true

- name: install apt-repo on ALT Linux
  package: name=apt-repo state=present
  become: true
  when: ansible_distribution_file_path == '/etc/altlinux-release'

- name: remember md5 hash of /etc/apt/sources.list
  command: >
    md5sum /etc/apt/sources.list
  register: sources_list_before_md5
  changed_when: False
  when: ansible_distribution_file_path == '/etc/altlinux-release'

- name: add apt tasks on ALT Linux
  command: >
    apt-repo add {{ item.id }}
  loop: "{{ kerneldev_apt_tasks|default([]) }}"
  loop_control:
    label: "{{ item.description }}"
  when: ansible_distribution_file_path == '/etc/altlinux-release'
  become: true

- name: compute md5 hash of /etc/apt/sources.list
  command: >
    md5sum /etc/apt/sources.list
  register: sources_list_after_md5
  changed_when: False
  when: ansible_distribution_file_path == '/etc/altlinux-release'

- name: update apt cache
  command: apt-get update
  become: true
  when:
    - ansible_distribution_file_path == '/etc/altlinux-release'
    - sources_list_after_md5.stdout != sources_list_before_md5.stdout

- name: install cross-binutils
  package: name=binutils-{{ item }} state=present
  with_items: "{{ cross_toolchains }}"
  become: true

- name: install C cross-compilers
  package: name=gcc-{{ item }} state=present
  with_items: "{{ cross_toolchains }}"
  become: true

- name: fixup cross-compilers on ALT Linux
  include_tasks: fixup-altlinux-cross-gcc.yml
  when:
    - ansible_distribution_file_path == '/etc/altlinux-release'
  loop: "{{ cross_toolchains }}"

- name: install kernel debugging helpers
  package: name={{ item }} state=present
  with_items:
    - picocom
  become: true

- name: install firmware update tools
  package: name={{ item }} state=present
  with_items:
    - flashrom
  become: true

- name: install Qt Creator on Debian
  package: name=qtcreator state=present
  become: true
  when: ansible_os_family == 'Debian'

- name: install Qt Creator on ALT Linux
  package: name=qt-creator-core state=present
  become: true
  when: ansible_distribution_file_path == '/etc/altlinux-release'
