---

- set_fact:
    kernel_build_packages:
      - bison
      - build-essential
      - ccache
      - dh-exec
      - git
      - fakeroot
      - flex
      - libncursesw5-dev 
      - libtinfo-dev
      - libssl-dev
  when:
    ansible_os_family == 'Debian'

- set_fact:
    kernel_build_packages:
      - bison
      - ccache
      - gcc
      - git-core
      - fakeroot
      - flex
      - libncursesw-devel
      - libtinfo-devel
      - libssl-devel
      - make
  when: ansible_distribution_file_path == '/etc/altlinux-release'

- name: install basic C development tools
  package: name={{ item }} state=present
  with_items: "{{ kernel_build_packages }}"
  become: true

- name: install cross-binutils
  package: name=binutils-{{ item }}-linux-gnu state=present
  with_items: "{{ kernel_target_architectures }}"
  become: true

- name: install C cross-compilers
  package: name=gcc-{{ item }}-linux-gnu
  with_items: "{{ kernel_target_architectures }}"
  become: true
