---

- set_fact:
    kernel_build_packages:
      - bison
      - build-essential
      - ccache
      - dh-exec
      - git
      - fakeroot
      - flex
      - libelf-dev
      - libncursesw5-dev 
      - libtinfo-dev
      - libssl-dev
      - openssl
  when:
    ansible_os_family == 'Debian'

- set_fact:
    kernel_build_packages:
      - bc
      - bison
      - ccache
      - cpio
      - gcc
      - git-core
      - fakeroot
      - flex
      - libelf-devel
      - libncursesw-devel
      - libtinfo-devel
      - libssl-devel
      - make
      - openssl
  when: ansible_distribution_file_path == '/etc/altlinux-release'

- name: install basic C development tools
  package: name={{ item }} state=present
  with_items: "{{ kernel_build_packages }}"
  become: true

- name: install cross-binutils
  package: name=binutils-{{ item }} state=present
  with_items: "{{ cross_toolchains }}"
  become: true

- name: install C cross-compilers
  package: name=gcc-{{ item }}
  with_items: "{{ cross_toolchains }}"
  become: true
