---

- name: install distcc
  package: name=distcc state=present
  become: true

- name: install native C compiler
  package: name={{ item }} state=present
  with_items:
    - gcc
  notify: restart distccd
  become: true

- name: install C cross-compilers
  package: name=gcc-{{ item }} state=present
  with_items: "{{ cross_toolchains }}"
  notify: restart distccd
  become: true

- name: configure distcc allowed nets
  lineinfile:
    path: /etc/default/distcc
    create: true
    line: "ALLOWEDNETS=\"{{ distccd_allowed_nets|join(' ') }}\""
    regexp: "^ALLOWEDNETS=.*"
  become: true
  notify: restart distccd

- name: set interfaces listened by distccd
  lineinfile:
    path: /etc/default/distcc
    line: "LISTENER=\"{{ distccd_listen|default(['0.0.0.0'])|join(' ') }}\""
    regexp: "^LISTENER=.*"
  become: true
  notify: restart distccd

- name: enable starting distccd
  lineinfile:
    path: /etc/default/distcc
    line: 'STARTDISTCC="true"'
    regexp: "^STARTDISTCC.*"
  become: true
  notify: restart distccd
