---

- name: install basic development tools on Debian
  package: name={{ item }} state=present
  with_items:
    - build-essential
    - cmake
    - g++
    - ninja-build
  when: ansible_os_family == 'Debian'
  become: true

- name: install basic development tools on ALT Linux
  package: name={{ item }} state=present
  with_items:
    - cmake
    - ctest
    - gcc-c++
    - man-pages
    - man-pages-posix
    - man-pages-posix-devel
    - ninja-build
    - patch
  when: ansible_distribution_file_path == '/etc/altlinux-release'
  become: true

- name: install git-cola and Qt Creator on Debian
  package: name={{ item }} state=present
  with_items:
    - "git-cola"
    - qtcreator
  when: ansible_os_family == 'Debian'
  become: true

- name: install Qt Creator and git-cola on ALT Linux
  package: name={{ item }} state=present
  loop:
    - "qt-creator-core"
    - "git-cola"
  when: ansible_distribution_file_path == '/etc/altlinux-release'
  become: true

- name: install Qt5/gtk integration tools on Debian
  package: name={{ item }} state=present
  with_items:
    - "qt5-gtk2-platformtheme"
    - qt5ct
  when: ansible_os_family == 'Debian'
  become: true

- name: install Qt5/gtk integration tools on ALT Linux
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "adwaita-qt5"
    - qt5ct
  when: ansible_distribution_file_path == '/etc/altlinux-release'
  become: true
