---

- name: kick systemd
  command: systemctl daemon-reload
  become: true

- name: restart distccd
  service: name=distccd state=restarted
  become: true

- name: update distcc symlinks
  command: "{{ distcc_local_prefix|default('/usr') }}/sbin/update-distcc-symlinks"
  become: true
