---

- name: install mkimage and friends
  apt_rpm: pkg={{ item }} state=present
  with_items:
    - mkimage
    - mkimage-preinstall
    - hasher
    - git-core
  become: true

- name: enable /proc in hasher chroots
  lineinfile:
    dest: /etc/hasher-priv/system
    line: "allowed_mountpoints=/proc"
    state: present
  become: true

- name: lift hsh-run timeout
  lineinfile:
    dest: /etc/hasher-priv/system
    line: "wlimit_time_elapsed=86400"
    state: present
  become: true

- name: create user
  user:
    name: "{{ hasher_user }}"
    state: present
  become: true
  when: hasher_user is defined

- name: check if user is already in hasher group
  command: >
    getent passwd {{ hasher_user }}_a
  register: user_a_getent
  failed_when: False
  when: hasher_user is defined

- name: add user to hasher group
  command: hasher-useradd {{ hasher_user }}
  become: true
  when:
    - hasher_user is defined
    - user_a_getent.rc|default(0) != 0
- name: add user to wheel group
  user:
    name: "{{ hasher_user }}"
    groups: wheel
    append: true
  become: true
  when:
    - hasher_user is defined
    - hasher_enable_wheel|default(true)|bool

- name: enable passwordless sudo for user
  copy:
    dest: "/etc/sudoers.d/{{ hasher_user }}"
    owner: root
    group: root
    mode: 0600
    content: "{{ hasher_user }} ALL=(ALL) NOPASSWD: ALL"
  become: true
  when:
    - hasher_user is defined
    - hasher_enable_nopasswd_sudo|default(true)|bool
