---

- name: restart systemd-binfmt
  service:
    name: systemd-binfmt
    state: restarted
  become: true

- name: apply sysctl.d knobs
  service:
    name: systemd-sysctl
    state: restarted
  become: true
