---

- name: ensure local mirror directory exists
  file:
    path: "{{ local_alt_mirror }}"
    state: directory

- name: download ALT Linux ISO images
  get_url:
    dest: "{{ local_alt_mirror }}/{{ item.url|basename }}"
    url: "{{ item.url }}"
    checksum: "sha256:{{ item.checksum.sha256 }}"
  loop: "{{ alt_images }}"

- name: ensure loop mount points exist
  file:
    path: "{{ alt_netinstall_dir }}/{{ item.alt_arch }}/{{ item.mountpoint|default('iso') }}"
    state: directory
  loop: "{{ alt_images }}"

- name: loop mount ISOs
  mount:
    path: "{{ alt_netinstall_dir }}/{{ item.alt_arch }}/{{ item.mountpoint|default('iso') }}"
    src: "{{ local_alt_mirror }}/{{ item.url|basename }}"
    fstype: iso9660
    opts: loop,ro,nodev,nosuid
    state: mounted
  loop: "{{ alt_images }}"
  become: true
