---

# setup passwordless sudo for the given user (default: current local user)
#
#

- set_fact:
    current_local_user: "{{ lookup('env', 'USER') }}"

- name: create my account
  user:
    name: "{{ admin_user|default(current_local_user) }}"
    state: present
    shell: /bin/bash
    password_lock: yes

- name: set ssh authorized keys from local key
  authorized_key:
    user: "{{ admin_user|default(current_local_user) }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present

- name: install sudo 
  package: name=sudo state=present

- name: add user to the wheel group
  user:
    name: "{{ admin_user|default(current_local_user) }}"
    groups: wheel
    append: true
  when:
    - ansible_distribution_file_path == '/etc/altlinux-release'

- name: configure passwordless sudo for admin user
  copy:
    dest: "/etc/sudoers.d/{{ admin_user|default(current_local_user) }}"
    owner: root
    group: root
    mode: 0600
    content: "{{ admin_user|default(current_local_user) }} ALL=(ALL) NOPASSWD: ALL"
