---

- name: install GNU screen
  package: name=screen state=present
  become: true

- name: configure GNU screen status line
  copy:
    src: templates/screenrc
    dest: "{{ lookup('env', 'HOME') }}/.screenrc"
    mode: 0644

- name: set proper LESS environment variable by default
  lineinfile:
    path: /etc/environment
    line: LESS="-RX"
  become: true

- name: install vipw on ALT Linux
  package:
    name: shadow-edit
    state: present
  when: ansible_distribution_file_path == '/etc/altlinux-release'
  become: true

- name: ensure /etc/environment is processed on ALT Linux
  lineinfile:
    path: /etc/pam.d/system-auth-common
    line: session optional pam_env.so envfile=/etc/environment
  when: ansible_distribution_file_path == '/etc/altlinux-release'
  become: true

- name: install vidir on ALT Linux
  package:
    name: moreutils
    state: present
  when: ansible_distribution_file_path == '/etc/altlinux-release'
  become: true
