---

- name: install GNU screen
  package: name=screen state=present
  become: true

- name: configure GNU screen status line
  copy:
    src: templates/screenrc
    dest: "{{ lookup('env', 'HOME') }}/.screenrc"
    mode: 0644

- name: set proper LESS environment variable by default
  lineinfile:
    path: /etc/environment
    line: LESS="-RX"
  become: true

- name: add xpra repository GPG key
  apt_key:
    id: 18ADB31CF18AD6BB
    url: "https://xpra.org/gpg.asc"
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: add xpra apt repository
  apt_repository:
    repo: "deb https://xpra.org {{ ansible_distribution_release }} main"
    filename: xpra
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: install xpra
  package: name=xpra state=present
  become: true
