---

- name: install GNU screen
  package: name=screen state=present
  become: true

- name: configure GNU screen status line
  copy:
    src: templates/screenrc
    dest: "{{ lookup('env', 'HOME') }}/.screenrc"
    mode: 0644

- name: set proper LESS environment variable by default
  lineinfile:
    path: /etc/environment
    line: LESS="-RX"
  become: true

- name: install vipw on ALT Linux
  package:
    name: shadow-edit
    state: present
  become: true
